export const CHANGE_SEARCH_FIELD = 'CHANGE_SEARCH_FIELD'

export const REQEUEST_ROBOTS_PENDING = 'REQEUEST_ROBOTS_PENDING'
export const REQEUEST_ROBOTS_SUCCESS = 'REQEUEST_ROBOTS_SUCCESS'
export const REQEUEST_ROBOTS_FAILED = 'REQEUEST_ROBOTS_FAILED'